### ISSUE TITLE
Offline Yeelight

### ISSUE THREAD

**Issue by controlboss** [mattmattmatt/node-red-contrib-yeelight-compat-hue#19]
i believe this issue is similar to others but when restarting node-red and the yeelight is offline (no power) the system continually restarts and it crashes the entire node-red environment.  is there a way to just timeout and retry every so often to reconnect?  here are the errors:

Error at 192.168.1.183:55443 { Error: connect EHOSTUNREACH 192.168.1.183:55443
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'EHOSTUNREACH',
  errno: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.1.183',
  port: 55443 }
22 May 07:02:17 - [info] [yeelight-compat-hue-config:Stacklight] Disconnected from 192.168.1.183:55443
Yeelight error { Error: connect EHOSTUNREACH 192.168.1.183:55443
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'EHOSTUNREACH',
  errno: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.1.183',
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Unit entered failed state.
nodered.service: Failed with result 'exit-code'.
nodered.service: Service hold-off time over, scheduling restart.
Stopped Node-RED graphical event wiring tool.

**Comment by ghost** [comment]
Same here, whole nodered went crazy because of one mostly unused lamp accidently turned off. Seems noone cares about this node anymore, maybe better to send command using python script.
