### ISSUE TITLE
Crashing NodeRED when deploy changes

### ISSUE THREAD

**Issue by enclude** [mattmattmatt/node-red-contrib-yeelight-compat-hue#25]
Hi, when I create and set configuration in NodeRED and Deploy the changes I got crash of node red. Log from console bellow. It is does not matter when I install this from CLI or "Pallete Manager" or Raspberry Pi 3 or 4. Always this error has occured. 

`25 Sep 13:09:45 - [info] Starting flows
25 Sep 13:09:45 - [info] Started flows
25 Sep 13:09:46 - [red] Uncaught Exception:
25 Sep 13:09:46 - SyntaxError: Unexpected token , in JSON at position 6
    at JSON.parse (<anonymous>)
    at parseResult (/home/pi/.node-red/node_modules/yeelight2/index.js:189:24)
    at Yeelight.parse (/home/pi/.node-red/node_modules/yeelight2/index.js:204:5)
    at Array.forEach (<anonymous>)
    at Yeelight.<anonymous> (/home/pi/.node-red/node_modules/yeelight2/index.js:40:8)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.
nodered.service: Service RestartSec=100ms expired, scheduling restart.
nodered.service: Scheduled restart job, restart counter is at 5.
Stopped Node-RED graphical event wiring tool.
Started Node-RED graphical event wiring tool.
25 Sep 13:09:48 - [info]
`

**Comment by nedisonn** [comment]
I have the same problem, and I can't find anything wrong with my nodes, yet I still get that message.

**Comment by michelefa1988** [comment]
Any updates / work arounds on this? :(
